### ISSUE TITLE
Implement replacing of ram payer in chaindb injection

### ISSUE THREAD

**Issue by afalaleev** [cyberway/cyberway#250]

**Comment by s-medvedev** [comment]
It is very dangerous to automatically change ram payer for all records. There are a number of cases where a change in ram payer is undesirable (one example is the storage of a balance in tokens, which always must be in ram of owner this tokens).
Therefore, instead of automatically changing ram payer, it was decided to shift this action to a smart contract. Smart-contract can known preferred ram payer by special intrinsic and use this value when insert record into database.
So this task is frozen.
